### ISSUE TITLE
Election committee CTA to join

### ISSUE THREAD

**Issue by logankilpatrick** [numfocus/elections#10]
Hey folks, what is the right mechanism to recruit community members to join this committee? Can we add a CTA in the readme? Is there a Google form to apply to join?

**Comment by mrocklin** [comment]
Hi @logankilpatrick 

Do you want people who will vet candidates, or people to run the election?  If the second I'd recommend recruiting them directly rather than having a fully open process (getting a group of self-selecting people to move forward cohesively is hard).

There is not currently a Google form.  You could add a CTA to the README, but currently I'm not sure that this repo gets any traffic.  

Historically Leah sent out an e-mail to project leaders saying that if they were interested they should reply to her.  Maybe you could repeat that process?  Text below:

### Leah's e-mail

Hello, projects and community leaders,

The NumFOCUS Board of Directors invites you to join us online for a NumFOCUS Town Hall Meeting on February 12 from 12:00 pm to 1:30 pm Central Time (invite to come). 

We will share our vision for the future of NumFOCUS and discuss plans for navigating our growth. As essential stakeholders, we value your input and look forward to your feedback and engagement. The meeting will be recorded, but we would like at least one representative from each project to attend.  


We also announce a Call For Members for our newly formed Election Committee. Membership will be comprised of board and community stakeholders who will be working on and supporting our election process. We would like to get the committee up and running as soon as possible. If you are interested in volunteering, please reply by February 21. We will get back to you with additional information.


Looking forward to "seeing" everyone on the 12th for the Town Hall!

All Our Best,
Leah, on behalf of the NumFOCUS Board of Directors

**Comment by tkoyama010** [comment]
It's a perfect answer! thanks.

> We also announce a Call For Members for our newly formed Election Committee. Membership will be comprised of board and community stakeholders who will be working on and supporting our election process. We would like to get the committee up and running as soon as possible. If you are interested in volunteering, please reply by February 21. We will get back to you with additional information.

Just curious, are the community leaders who received the email the only ones entitled to reply and participate in this email? May a community leader refer a community member who is willing to participate?

**Comment by pavithraes** [comment]
Sharing a quick update.

The call for new members is mentioned in:
- Repo README
- [NumFOCUS Board Elections: Addressing the Need for Transparency and Equity](https://numfocus.medium.com/the-board-believes-a-strong-transparent-and-equitable-governance-structure-is-essential-to-2e400761d3c0)

There are plans to announce this in:
- Upcoming NumFOCUS newsletter
- Dedicated email to various community members, like Leah previous email that Matt mentioned above

As a lightweight option, we decided folks can email [electioncommittee@numfocus.org](mailto:electioncommittee@numfocus.org) indicating their interest in joining.

As for recruiting specific individuals, while there are currently no plans or capacity for this, I do agree that it can be helpful. I'll mention it in the weekly sync to check if NumFOCUS can do this.

**Comment by tkoyama010** [comment]
@all-contributors please add @pavithraes for question

**Comment by pavithraes** [comment]
Closing as complete
