### ISSUE TITLE
Describe obligations of board members

### ISSUE THREAD

**Issue by mrocklin** [numfocus/elections#7]
Board members will need to know what they're getting into.  @lsilen I think that we're relying on you for this (let me know if this isn't something you can do and I'll try to find someone else).  My hope is that this isn't a very heavy lift, and is probably just a few bullet points that you write down casually.

**Comment by lsilen** [comment]
I can share a list of board responsibilities.

**Comment by aterrel** [comment]
Is there something the committee seeks beyond the listings in the by laws?

Section 4. Duties
--
It shall be the duty of the Board to:

a. Perform any and all duties imposed on them collectively or individually by law, by the Articles of Incorporation, or by these bylaws;
b. Appoint and remove, employ and discharge, and, except as otherwise provided in these bylaws, prescribe the duties and fix the compensation, if any, of all officers, agents, and employees of the Corporation;
c. Supervise all officers, agents, and employees of the Corporation to assure that their duties are performed properly;
d. Meet at such times and places as required by these bylaws;
e. Register their email addresses with the Secretary of the Corporation, and notices of mectings emailed to them at such addresses shall be valid notices thereof.

**Comment by aterrel** [comment]
I wrote some thoughts on this question for the election committee's consideration: https://docs.google.com/document/d/144-0_Fhnj2b1CORnT7tKN2xkT-Qn7qbikBs81-1Ltuo/edit?usp=sharing

**Comment by mrocklin** [comment]
I like the writeup Andy.  I encourage you to put it on your blog or
somewhere else that's more published.  There are cases in the past when I
would have linked to this in conversation.

**Comment by ivanov** [comment]
@aterrel wrote:
> Is there something the committee seeks beyond the listings in the [Bylaws](https://numfocus.org/wp-content/uploads/2020/04/NumFOCUS-Bylaws-Approved-16-May-2019.pdf)?

Yes. The separation of the Board into a Technical and Administrative will follow this election, so is relevant for potential candidates of this election.

I reproduce the relevant portion from the minutes on [March 18th](https://docs.google.com/document/d/1zEYZfbOug2xMzvKTQ-1txtrgj-5-FOslle7Dd2RBzOM/edit) below: 

> Leah: The board is splitting into technical and administrative. After the upcoming election (with 7 seats?), we’ll need to split.
Pavithra: It may nice to keep these separate?
Lars: Will they all be the “Board”
Leah: yes, they’ll just have different sets of responsibilities
Paul: Did bylaws change?
Leah: Yes, we’ll need to update number of members
Paul: Will the tech / admin spilt also be mentioned in the bylaws?
Leah: yes, this need to be spelled out in the bylaws. The current bylaws don’t hinder this, except the 9 member requirements. This was decided just last week at the board meeting.

The working draft that contains separated responsibities we have is [here](https://docs.google.com/document/d/1mbFw-gqulvQFSXQOKLWcxSCD_b-0VT5oUAV6kOsG6j0/edit#heading=h.cs7r1nnu67ou)

**Comment by pavithraes** [comment]
We now have https://github.com/numfocus/elections/blob/main/board-responsibilities.md with some more details.

I'll close this issues as complete. Please open new issues/discussions with any specific questions about responsibilities that need to be answered by this doc. :)

@aterrel I think your write-up provides useful perspective. If you get a chance to publish it, we can add it as a reference in the doc.

**Comment by aterrel** [comment]
Thank you for the encouragement. I published one here: http://andy.terrel.us/blog/2024/05/03/role-of-board-member/

The second post hasn't been fully edited, but will work in getting that out.

**Comment by tkoyama010** [comment]
@all-contributors please add @aterrel for blog
